version: '3.3'

services:
  web:
    build: ./pet_blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pet_blog/:/pet_blog_django
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev